name: example
description: A new Flutter application.
version: "1.0.0"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_svg: ^0.21.0-nullsafety.0 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  runtime_arb:
    path: ../runtime_arb

builders:
  r_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  r_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
      - lib/assets/
      - lib/assets/sub/
      - lib/assets/sub/ignore1/
      - lib/assets/sub/ignore2/
      - lib/assets/sub/sub/
      - lib/assets/sub2/sub2.txt
      - lib/assets/sub2/

  fonts:
      - family: TestFont
        fonts:
          - asset: lib/assets/fonts/Roboto-Thin.ttf

r_flutter:
  intl: lib/i18n/en.arb
  ignore:
    - lib/assets/sub/ignore1
    - lib/assets/sub/ignore2
    - lib/i18n
  asset_classes:
    ".svg":
      import: asset_classes.dart
      class: SvgFile